### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by NN---** [jowave/vcard2to3#8] opened 2020-10-23 08:03 UTC
Using Python 3.9 and regular VCF 2.1.

**Comment by jowave** [comment] 2020-10-23 14:55
To be able to help you, I need more information:
* What does not work? What command did you execute?
* Please add the error message.
* Please add an example vcf file to reproduce the error.

I tested with Python 3.9 using docker and it worked fine for `example.vcf` using:

    docker run --rm -v "$(pwd):/vcard" -w /vcard --user "$(id -u):$(id -g)" quay.io/python-devs/ci-image:master python3.9 vcard2to3.py examples.vcf

**Comment by NN---** [comment] 2020-10-23 15:30
No error message
Just creates empty output file.
Running in Windows.
The vcf is taken from old Nokia phone:)

**Comment by NN---** [comment] 2020-10-23 15:30
I’ll put a VCF here later

**Comment by KBSchmidt** [comment] 2020-12-02 11:05
@NN--- same. But you can import it to google as a csv! Then you can download them as a proper vfc, and can event import it to iCloud

**Comment by NN---** [comment] 2020-12-02 11:11
@KBSchmidt This is exactly what I did ! :)
It would be nicer to have an offline solution without sending all your contacts to Google.

**Comment by jowave** [comment] 2020-12-07 13:54
I was able to test on Windows today and had encoding issues with my test file. Since Windows 10 still uses some platform dependendent file encoding instead of utf-8, I added an option to specify the input file encoding. This might help you as well.

Apart from the encoding issues, the scripts work fine for me. Can you try running (in cmd or powershell console):

    python .\vcard2to3.py --in_encoding utf-8 --out_encoding utf-8 .\examples.vcf

which should produce a file `examples.vcf.converted`.

If your input files contain at least one valid vCard an output file should be produced or an error message should be printed. If you provide a (minimal) non-working example, I might be able to investigate further.

**Comment by jowave** [comment] 2022-08-26 15:17
Closing, since no example was provided.

**Closed as not planned by jowave** 2022-08-26 15:17 UTC
Labels: need feedback
